FTCS/FTCS/ViewModels/Reports/CSQPRGraduateVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using FTCS.Models;
using FTCS.Services;

namespace FTCS.ViewModels.Reports
{
    public class CSQPRGraduateVM
    {
        public string Code { get; set; }
        public string DepartmentName { get; set; }
        public int AllSection { get; set; }
        public int TotalCourse { get; set; }
        public int GraduateCourse { get; set; }
        public int GraduateCoursePercent { get; set; }
        public int AcademicCourse { get; set; }
        public int AcademicCoursePercent { get; set; }
        public int ProfessionalCourse { get; set; }
        public int ProfessionalCoursePercent { get; set; }
        public int GaCourse { get; set; }
        public int GaCourseCoursePercent { get; set; }
        public int TranscriptMissed { get; set; }
        public IEnumerable<String> TranscriptMissingList { get; set; }
        public int TotalCoursePercent { get; internal set; }
    }
}

FTCS/FTCS/ViewModels/Reports/CSQPRReportVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FTCS.ViewModels.Reports
{
    public class CSQPRReportVM
    {
        public IEnumerable<CSQPRGraduateVM> CSQPRGraduate { get; set; }
        public CSQPRTotalVM CSQPRTotal { get; set; }
    }
}

FTCS/FTCS/ViewModels/Reports/CSQPRTotalVM.cs
using NUnit.Framework.Constraints;

namespace FTCS.ViewModels.Reports
{
    public class CSQPRTotalVM
    {
        public int TotalUnspecified;
        public int TotalAcademicNumber { get; internal set; }
        public int TotalAcademicPercent { get; internal set; }
        public int TotalCourseNumber { get; internal set; }
        public int TotalCoursePercent { get; internal set; }
        public int TotalProfessionallyQualified { get; set; }
        public int TotalProfessionallyQualifiedPercent { get; set; }
        public int TotalGraduateAssistants { get; set; }
        public int TotalGraduateAssistantsPercent { get; set; }
        public int TotalMissingTranscripts { get; set; }
    }
}

FTCS/FTCS/ViewModels/Reports/CSQPRUndergraduateVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FTCS.ViewModels.Reports
{
    public class CSQPRUndergraduateVM
    {
        public string Code { get; set; }
        public string DepartmentName { get; set; }
        public int AllSection { get; set; }
        public int TotalCourse { get; set; }
        public int UndergraduateCourse { get; set; }
        public int UndergraduateCoursePercent { get; set; }
        public int AcademicCourse { get; set; }
        public int AcademicCoursePercent { get; set; }
        public int ProfessionalCourse { get; set; }
        public int ProfessionalCoursePercent { get; set; }
        public int GaCourse { get; set; }
        public int GaCourseCoursePercent { get; set; }
        public int TranscriptMissed { get; set; }
        public IEnumerable<String> TranscriptMissingList { get; set; }
        public int TotalCoursePercent { get; internal set; }
    }
}

FTCS/FTCS/ViewModels/Reports/ChartVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FTCS.ViewModels.Reports
{
    public class ChartVM
    {
        public object UnspecifiedDepartments { get; set; }
        public CSQPRTotalVM Totals { get; set; }
    }
}

FTCS/FTCS/ViewModels/Reports/CourseRecordsBySemesterVM.cs
using FTCS.Models;
using System.Collections;
using System.Collections.Generic;
using FTCS.Services;
using FTCS.Services.Implementation;

namespace FTCS.ViewModels
{
    public class CourseRecordsBySemesterVM
    {
        public Semester Name { get; set; }
        public IEnumerable<string> Records { get; set; }
    }
}

FTCS/FTCS/ViewModels/Reports/CourseSectionQualificationsPercentageReportVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FTCS.Controllers;

namespace FTCS.ViewModels.Reports
{
    public class CourseSectionQualificationsPercentageReportVM
    {
        public List<SelectListItem> Years { get; set; }
        public IEnumerable<CSQPRGraduateVM> GraduateReport { get; set; }

        public IEnumerable<CSQPRUndergraduateVM> UndergraduateReport { get; set; }
        public string AcademicYearForReport { get; set; }
        public CSQPRTotalVM UndergraduateTotal { get; internal set; }
        public CSQPRTotalVM GraduateTotal { get; internal set; }
        public CSQPRTotalVM CSQPRTotal { get; internal set; }
    }
}

FTCS/FTCS/ViewModels/Reports/FCRTableVM.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace FTCS.ViewModels
{
    public class FCRTableVM<T> where T : class
    {
        public List<T> TableItemVM { get; set; }

        public List<SelectListItem> Department { get; set; }

        public List<SelectListItem> Semester { get; set; }

        public ReportFilterBarVM ReportFilterBarVM { get; set; }

    }
}

FTCS/FTCS/ViewModels/Reports/FacultyCredentialsReportVM.cs
using System.ComponentModel.DataAnnotations;
using FTCS.Services.Implementation;

namespace FTCS.ViewModels
{
    public class FacultyCredentialsReportVM
    {
        public string TeacherId { get; set; }
        public string FacultyName { get; set; }

        public string Semester { get; set; }

        public string Course { get; set; }

        public Qualification Credential { get; set; }
        public string CourseDescription { get; set; }
        public string SelectedCredentialId { get; set; }
        public string CourseRubric { get; set; }
        public string CourseNumber { get; set; }
        public string CourseCode { get; internal set; }
    }
}

FTCS/FTCS/ViewModels/Reports/FacultyRosterVM.cs
using FTCS.Models;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using FTCS.Services;
using FTCS.ViewModels.FacultyProfile;

namespace FTCS.ViewModels
{
    public class FacultyRosterVM
    {
        [Display(Name="Full Name")]
        public string Name { get; set; }
        public TeacherType TeacherType;
        [Display(Name = "Academic Degrees")]
        public string AcademicDegree { get; set; }
        public string Department { get; set; }
        [DisplayFormat(NullDisplayText = "None")]
        public string Narrative { get; set; }
        [Display(Name="Academic Degrees")]
        public IEnumerable<string> AcademicDegrees { get; set;}
        [Display(Name="Courses Taught")]
        public IOrderedEnumerable<CourseRecordsBySemesterVM> CourseRecords { get; set; }
        [Display(Name="Professional Qualifications")]
        public ExperienceSummaryVM SummaryVm { get; set; }
        
    }
}

FTCS/FTCS/ViewModels/Reports/GraduateCourseByDepartmentVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FTCS.ViewModels.Reports
{
    public class GraduateCourseByDepartmentVM
    {
        public string Code { get; set; }
        public string DepartmentName { get; set; }
        public int AllCourse { get; set; }
        public int TotalCourse { get; set; }
        public int GraduateCourse { get; set; }
        public int AcademicCourse { get; set; }
        public int ProfessionalCourse { get; set; }
        public int GaCourse { get; set; }
        public double GraduateCoursePercent { get; set; }
        public double AcademicCoursePercent { get; set; }
        public double ProfessionalCoursePercent { get; set; }
        public double GaCourseCoursePercent { get; set; }
        public int TranscriptMissed { get; set; }
        public IEnumerable<TranscriptMissListVM> TranscriptMissList { get; set; }
    }
}

FTCS/FTCS/ViewModels/Reports/LicenseVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace FTCS.ViewModels.Reports
{
    public class LicenseVM
    {
        public String Name { get; set; }
        [Display(Name = "Awarded By")]
        public String AwardedBy { get; set; }
        public string AwardMonth { get; set; }
        public int AwardYear { get; set; }
        public string ExpireMonth { get; set; }
        public int ExpireYear { get; set; }

        [Display(Name = "Date Awarded")]
        public String DateAwarded => $"{AwardMonth} {AwardYear}";

        [Display(Name = "Date Expires")]
        public String DateExpires => $"{ExpireMonth} {ExpireYear}";
    }
}

FTCS/FTCS/ViewModels/Reports/ReportVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FTCS.ViewModels
{
    public class ReportVM<T> where T :class 
    {
        public IEnumerable<T> ReportLines { get; set; }
        public ReportFilterBarVM ReportFilterBarVM { get; set; }
    }
}

FTCS/FTCS/ViewModels/Reports/TranscriptMissVM.cs
namespace FTCS.ViewModels.Reports
{
    public class TranscriptMissVM
    {
    }
}

FTCS/FTCS/Controllers/ReportsController.cs
using FTCS.Interfaces;
using FTCS.Services;
using FTCS.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using FTCS.Models;
using FTCS.Services.Implementation;
using FTCS.Services.Interfaces;
using Rotativa;
using FTCS.ViewModels.Reports;

namespace FTCS.Controllers
{
    public class ReportsController : Controller
    {
        
        private readonly IReportService _reportService;
        private readonly IDepartmentService _departmentService;
        private readonly IFacultyService _facultyService;
        private const string DefaultDepartmentSortOrder = "NAME_asc";
        private const int GradAssistantFacultyType = 0;
        private const int FullTimeFacultyType = 4;
        private const int CacheDuration = 60 * 60 * 2; //cache duration every two hours


        public ReportsController()
        {
            var context = new FTCSEntities();
            _departmentService = new DepartmentService(context);
            _reportService = new ReportService(context, _departmentService);
            _facultyService = new FacultyService(context);
        }
        public ReportsController(IReportService reportService, IDepartmentService departmentService, IFacultyService facultyService)
        {
            _reportService = reportService;
            _departmentService = departmentService;
            _facultyService = facultyService;
        }
        // GET: Reports

        public ActionResult GradAssistantRoster(int? year, bool? pdf)
        {
            var isPdf = pdf ?? false;
            var defaultYear = AcademicYear.GetCurrentAcademicYear().First().Year;
            var convertedYear = year ?? defaultYear;
            ViewBag.Year = convertedYear;
            var listOfGradAssistants = _reportService.GetFacultyRoster(convertedYear, GradAssistantFacultyType, "").OrderBy(log => log.Department);
            if (isPdf)
            {
                return new ViewAsPdf("GradAssistantRosterPDF",listOfGradAssistants);
            }
            var model = new ReportVM<FacultyRosterVM>
            {
                ReportLines = listOfGradAssistants,
                ReportFilterBarVM = new ReportFilterBarVM {}
                   
            };
            return View(model);
        }
        public ActionResult FacultyRoster(int? year, string department, int? facultyType, bool? pdf)
        {
            var isPdf = pdf ?? false;
            var defaultYear = AcademicYear.GetCurrentAcademicYear().First().Year;
            var convertedYear = year ?? defaultYear;
            facultyType = facultyType ?? FullTimeFacultyType;
            var listOfDepartments = _departmentService.GetListOfDepartments(string.Empty, string.Empty, DefaultDepartmentSortOrder);
            department = string.IsNullOrEmpty(department) ? listOfDepartments.FirstOrDefault()?.DEPARTMENT_CODE : department;
            var listOfFacultyTypes = _facultyService.GetFacultyTypes();
            var listOfGradAssistants = _reportService.GetFacultyRoster(convertedYear, facultyType, department);
            ViewBag.Year = convertedYear;
            var facultyTypeVMs = listOfFacultyTypes as IList<FacultyTypeVM> ?? listOfFacultyTypes.ToList();
            ViewBag.Faculty = facultyTypeVMs.FirstOrDefault(f => f.Id == facultyType.Value)?.TypeName;
            ViewBag.Department = listOfDepartments.FirstOrDefault(d => d.DEPARTMENT_CODE == department)?.NAME;
            if (isPdf)
            {
                return new ViewAsPdf("FacultyRosterPDF", listOfGradAssistants);
            }
            var model = new ReportVM<FacultyRosterVM>
            {
                ReportLines = listOfGradAssistants,
                ReportFilterBarVM = new ReportFilterBarVM(listOfDepartments, facultyTypeVMs)
            };
            return View(model);
        }

        public ActionResult FacultyCredentialsReport(string department, int? year, bool? pdf)
        {
            var defaultYear = AcademicYear.GetCurrentAcademicYear().First().Year;
            var convertedYear = year ?? defaultYear;
            ViewBag.Year = convertedYear;
            var academicYearString = AcademicYear.GetAcademicYearStringForYear(convertedYear);
            var listOfDepartments = _departmentService.GetListOfDepartments(string.Empty, string.Empty, DefaultDepartmentSortOrder);
            department = string.IsNullOrEmpty(department) ? listOfDepartments.FirstOrDefault()?.DEPARTMENT_CODE : department;
            ViewBag.Title = $"Faculty Credentials Report: {department} {academicYearString}";
            ViewBag.Department = department;
            ViewBag.SemesterYear = academicYearString;
            var isPdf = pdf ?? false;
            var facultyCredentialsReport = _reportService.GetFacultyCredentialsReport(department,convertedYear);
            var semesterMenu = AcademicYear.GetSemesterYearOptions(defaultYear, true);
            var departmentMenu = _departmentService.GetListOfDepartmentSelectListItems();
            if (isPdf)
            {
                return new ViewAsPdf("FacultyCredentialsReportPDF", facultyCredentialsReport);
            }
            var model = new FCRTableVM<FacultyCredentialsReportVM>
            {
                TableItemVM = facultyCredentialsReport.ToList(),
                Department = departmentMenu,
                Semester = semesterMenu,
                ReportFilterBarVM = new ReportFilterBarVM { }
            };
            return View(model);
        }

        public ActionResult CourseSectionQualificationPercentageReport(int? years, bool? pdf)
        {
            var isPdf = pdf ?? false;
            var academicYear = AcademicYear.GetCurrentAcademicYear();
            var defaultYear = academicYear.First().Year;
            var convertedYear = years ?? defaultYear;
            var ReportInfo = _reportService.GetCourseSectionQualificationPercentageReport(convertedYear);

            
            var report = new CourseSectionQualificationsPercentageReportVM()
            {
                AcademicYearForReport = AcademicYear.GetAcademicYearStringForYear(convertedYear),
                UndergraduateReport = ReportInfo.UndergraduateReport,
                GraduateReport = ReportInfo.GraduateReport,
                UndergraduateTotal = ReportInfo.UndergraduateTotal,
                GraduateTotal = ReportInfo.GraduateTotal,
                CSQPRTotal = ReportInfo.CSQPRTotal,
                Years = ReportFilterBarVM.GenerateSelectYears(academicYear.ElementAt(0).Year)
            };
            if (isPdf)
            {
                return new ViewAsPdf("CourseSectionQualificationPDF", report);
            }

            return View("CourseSectionQualificationsPercentageReport", report);
        }

        [OutputCache(Duration = CacheDuration)]
        public JsonResult Credentials()
        {
            var result = _reportService.GetFacultyCredentialsSummary();
            return Json(result,JsonRequestBehavior.AllowGet);
        }
        protected override void Dispose(bool disposing)
        {
            _facultyService.Dispose();
            _departmentService.Dispose();
            _reportService.Dispose();
            base.Dispose(disposing);
        }
    }
}

FTCS/FTCS/Views/Reports/CourseSectionQualificationPDF.cshtml
@model CourseSectionQualificationsPercentageReportVM
@using FTCS.ViewModels.Reports

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Course Section Qualification Percentage Report</title>
    <link rel="stylesheet" href="~/Content/bootstrap.css" />
    <link rel="stylesheet" href="~/Content/Site.css" type="text/css" />
    <link rel="stylesheet" href="~/Content/PDF.css" type="text/css"/>
</head>
<body>
    <div class="row content-title">
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
            <h2>Course Section Qualification Percentage Report</h2>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 col-right">
            <h3>@Model.AcademicYearForReport</h3>
        </div>
    </div>
    @Html.Partial("_CSQPRUndergraduate", @Model)
    @Html.Partial("_CSQPRGraduate", @Model)
    @Html.Partial("_CSQPRGrandTotals", Model)
</body>
</html>

FTCS/FTCS/Views/Reports/CourseSectionQualificationsPercentageReport.cshtml
@model CourseSectionQualificationsPercentageReportVM
@using FTCS.ViewModels.Reports;

@{
    ViewBag.Title = "Course Section Qualifications Percentage Report";
}

<div class="container">
    <!--Heading section-->
    <div class="row content-title">
        <div class="col-lg-10 col-md-10 col-sm-10 col-xs-10 padding-top-4">
            <h1 class="col-left">Course Section Qualifications Percentage Report</h1>
        </div>
        <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2 col-right padding-top-2">
            @Html.ActionLink("View PDF", "CourseSectionQualificationPercentageReport",
                new { Years = Request.QueryString["Years"], pdf = true },
                new { id = "pdf-button", @class = "btn report-convert-button rounded-blue-button shadow-box-gray", target = "_blank" })
        </div>
    </div>
    <div class="row hr-yellow">
        <hr />
    </div>
    <!--Filter section-->
    <div class="row">
        @using (@Html.BeginForm("CourseSectionQualificationPercentageReport", "Reports", FormMethod.Get, new { @id = "report-filter" }))
        {
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 col-right">
                <label class="label-small">Academic Year:</label>
                @Html.DropDownList("Years", Model.Years , new { @class = "select-box glow-blue" })
            </div>
        }
    </div>
    <!--Grand Totals Table-->
    @Html.Partial("_CSQPRGrandTotals",Model)
    <!--Grad/Undergrad Tabs section-->
    <div class="sub-content">
        <div class="row menu-row padding-top-2">
            <div id="undergraduate-button" class="btn btn-default menu-button active">
                Undergraduate
                <div class="triangle-outer" style="display: block;"></div>
                <div class="triangle-inner" style="display: block;"></div>
            </div>
            <div id="graduate-button" class="btn btn-default menu-button">
                Graduate
                <div class="triangle-outer" style="display: none;"></div>
                <div class="triangle-inner" style="display: none;"></div>
            </div>
        </div>
        <hr />
        
        <!--Grad/Undergrad Panel Section-->
        <div class="row container">
            <div id="undergraduate-panel" style="display: block;" class="panel">
                <div class="row padding-top-2">
                    <h2 class="col-left">@Model.AcademicYearForReport</h2>
                    @Html.Partial("_CSQPRUndergraduate", @Model)
                </div>
            </div>
            <div id="graduate-panel" style="display: none;" class="panel">
                <div class="row padding-top-2">
                    <h2 class="col-left">@Model.AcademicYearForReport</h2>
                    @Html.Partial("_CSQPRGraduate", @Model)
                </div>
            </div>
        </div>  
    </div>
</div>

@Scripts.Render("~/Scripts/FTCS/sub-menu-noajax.js")

FTCS/FTCS/Views/Reports/FacultyCredentialsReport.cshtml
@model FCRTableVM<FacultyCredentialsReportVM>
@using System.Web.UI.WebControls
@using FTCS.ViewModels;
@using FTCS.App_Code;
@using FTCS.Services.Implementation;

@{
    ViewBag.Title = "Faculty Credentials Report";
}

<div class="container">
    <!--Heading section-->
    <div class="row content-title">
        <div class="col-lg-6 col-md-8 col-sm-10 col-xs-10 padding-top-4">
            <h1 class="col-left">Faculty Credentials Report</h1>
        </div>
        <div class="col-lg-6 col-md-4 col-sm-2 col-xs-2 col-right padding-top-2">
            @Html.ActionLink("Convert to PDF", "FacultyCredentialsReport", new
            {
               Department = Request.QueryString["Department"],
               SemesterYear = Request.QueryString["SemesterYear"],
               Pdf = true
            }, new { id = "pdf-button", @class = "btn report-convert-button rounded-blue-button shadow-box-gray", target = "_blank" })
        </div>
    </div>
    <div class="row hr-yellow">
        <hr/>
    </div>
    <!--Filter section-->
    <div class="row">
        @using (Html.BeginForm("FacultyCredentialsReport", "Reports", FormMethod.Get))
        {
            <div class="col-lg-10 col-md-10 col-sm-12 col-xs-12 col-right padding-bottom-2">
               
                <label class="label-small">Department:</label>
                @Html.DropDownList("department", Model.Department, new {@class="select-box glow-blue"})
                
                <!--Semester Year-->
                <label class="label-small">Semester Year:</label>                
                @Html.DropDownList("Year", Model.ReportFilterBarVM.Years, new { @class = "select-box glow-blue" })
            </div>
            <div class="col-lg-2 col-md-2 col-sm-12 col-xs-12 col-right padding-bottom-2">
                <input id="submit-button" class="btn report-submit-button rounded-blue-button shadow-box-gray" type="submit" value="Submit"/>
            </div>
        }
    </div>
    <!--Table Section-->
    <div class="row">
        <table class="table table-striped table-condensed content-table">
            <thead>
                <tr>
                    <th class="col-lg-3 col-md-3 col-sm-3 col-xs-3">Faculty Name</th>
                    <th class="col-lg-3 col-md-3 col-sm-3 col-xs-3">Semester</th>
                    <th class="col-lg-3 col-md-3 col-sm-3 col-xs-3">Course</th>
                    <th class="col-lg-3 col-md-3 col-sm-3 col-xs-3">Credential</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.TableItemVM)
                {
                    <tr>
                        <td class="@CSSHelper.backgroundRedIf(item.Credential.Description == "Unspecified")">@Html.DisplayFor(modelItem => item.FacultyName)</td>
                        <td class="@CSSHelper.backgroundRedIf(item.Credential.Description == "Unspecified")"> @Html.DisplayFor(modelItem => item.Semester)</td>
                        <td class="@CSSHelper.backgroundRedIf(item.Credential.Description == "Unspecified")">@Html.DisplayFor(modelItem => item.Course)</td>
                        <td class="@CSSHelper.backgroundRedIf(item.Credential.Description == "Unspecified")">@item.Credential.Description</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

FTCS/FTCS/Views/Reports/FacultyRoster.cshtml
@model  ReportVM<FacultyRosterVM>
@using FTCS.ViewModels;

@{
    ViewBag.Title = "Faculty Roster Report";
}

<div class="container">
    <!--Heading section-->
    <div class="row content-title">
        <div class="col-lg-6 col-md-6 col-sm-10 col-xs-10 padding-top-4">
            <h1 class="col-left">Faculty Roster Report</h1>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-2 col-xs-2 col-right padding-top-2">
            @Html.ActionLink("Convert to PDF", "FacultyRoster",
            new { department = Request.QueryString["Department"], FacultyType = Request.QueryString["FacultyType"], Year = Request.QueryString["Year"], pdf = true },
                new { id = "pdf-button", @class = "btn report-convert-button rounded-blue-button shadow-box-gray", target = "_blank" })
        </div>
    </div>
    <div class="row hr-yellow">
        <hr />
    </div>
    <!--Filter section-->
    <div class="row">
        @using (@Html.BeginForm("FacultyRoster", "Reports", FormMethod.Get, new { @id = "report" }))
        {
            <div class="col-lg-10 col-md-12 col-sm-12 col-xs-12 col-right padding-top-2">
                <label class="label-small">Department:</label>
                @Html.DropDownList("Department", Model.ReportFilterBarVM.Departments, new { @class = "select-box glow-blue" })
                <label class="label-small">Faculty Type:</label>
                @Html.DropDownList("FacultyType", Model.ReportFilterBarVM.Faculty, new { @class = "select-box glow-blue" })
                <label class="label-small">Academic Year:</label>
                @Html.DropDownList("Year", Model.ReportFilterBarVM.Years, new { @class = "select-box glow-blue" })
            </div>
            <div class="col-lg-2 col-md-12 col-sm-12 col-xs-12 col-right padding-top-2">
                <input id="report-filter-submit" class="btn report-submit-button rounded-blue-button shadow-box-gray" type="submit" />
            </div>
        }
    </div>
    <!--Legend section-->
    <div class="row content-title">
        <div class="col-lg-6 col-md-8 col-sm-10 col-xs-10">
            <h2 class="col-left">Legend</h2>
            <div class="hr-yellow">
                <hr />
            </div>
        </div>
    </div>
    <div class="row legend">
        <p>
            Faculty Name: (F) = Full Time,  (P) = Part Time, (GA) = Graduate Assistant
        </p>
    </div>
    <!--Table section-->
    <div class="row padding-top-2">
        <table class="table table-striped table-condensed content-table">
            <thead>
                <tr>
                    <th class="col-lg-2 col-md-2 col-sm-2 col-xs-2">Faculty Name</th>
                    <th class="col-lg-3 col-md-3 col-sm-3 col-xs-3">Academic Degrees</th>
                    <th class="col-lg-3 col-md-3 col-sm-3 col-xs-3">Courses Taught</th>
                    <th class="col-lg-4 col-md-4 col-sm-4 col-xs-4">Professional Qualifications</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.ReportLines)
                {
                    <tr>
                        <td>@Html.DisplayFor(model => item.Name) @Html.DisplayFor(model => item.TeacherType.ShortDescription)</td>
                        <td>
                            <ul>
                                @foreach (var degree in item.AcademicDegrees)
                                {
                                    <li>@Html.DisplayFor(model => degree)</li>
                                }
                            </ul>
                        </td>
                        <td>
                            @foreach (var courseRecord in item.CourseRecords)
                            {
                                <ul>
                                    <li>
                                        @courseRecord.Name.ToString()
                                        <ul>
                                            @foreach (var course in courseRecord.Records)
                                            {
                                                <li>
                                                    @Html.DisplayFor(model => course)
                                                </li>
                                            }
                                        </ul>
                                    </li>
                                </ul>
                            }
                        </td>
                        <td>
                            <ul>
                                @if (item.SummaryVm.Narrative == null && !item.SummaryVm.WorkExperience.Any())
                                {
                                    <li>None Required</li>
                                }
                                else
                                {
                                    <li>
                                        Narrative

                                        <ul>
                                            <li>
                                                @Html.DisplayFor(model => item.SummaryVm.Narrative)
                                            </li>
                                        </ul>
                                    </li>
                                    if (item.SummaryVm.WorkExperience.Any())
                                    {
                                        <li>
                                            Related Work Experience

                                            <ul>
                                                @foreach (var experience in item.SummaryVm.WorkExperience)
                                                {
                                                    <li>@Html.DisplayFor(model => experience)</li>
                                                }
                                            </ul>
                                        </li>
                                    }
                                }
                            </ul>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>