FTCS/FTCS/Models/CONCENTRATION.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONCENTRATION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONCENTRATION()
        {
            this.FACULTY_CONCENTRATION_COORDINATION = new HashSet<FACULTY_CONCENTRATION_COORDINATION>();
            this.FACULTY_CONCENTRATION_COORDINATION_RESPONSIBILITIES = new HashSet<FACULTY_CONCENTRATION_COORDINATION_RESPONSIBILITIES>();
            this.FACULTY_CONCENTRATION_QUALIFICATION = new HashSet<FACULTY_CONCENTRATION_QUALIFICATION>();
        }
    
        public string CODE { get; set; }
        public string NAME { get; set; }
        public string PROGRAM { get; set; }
    
        public virtual PROGRAM PROGRAM1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACULTY_CONCENTRATION_COORDINATION> FACULTY_CONCENTRATION_COORDINATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACULTY_CONCENTRATION_COORDINATION_RESPONSIBILITIES> FACULTY_CONCENTRATION_COORDINATION_RESPONSIBILITIES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACULTY_CONCENTRATION_QUALIFICATION> FACULTY_CONCENTRATION_QUALIFICATION { get; set; }
    }
}

FTCS/FTCS/ViewModels/ProgramOfStudy/AddProgramOfStudyVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FTCS.ViewModels
{
    public class AddProgramOfStudyVM
    {
        public List<SelectListItem> SelectProgram { get; set; }

        public List<SelectListItem> SelectLevel { get; set; }

        public List<SelectListItem> SelectCoordinator { get; set; }
        public List<SelectListItem> SelectDepartment { get; set; }
    }
}

FTCS/FTCS/ViewModels/ProgramOfStudy/ProgramOfStudyVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FTCS.ViewModels
{
    public class ProgramOfStudyVM
    {
        public string Program { get; set; }

        public string Level { get; set; }

        public string Coordinator { get; set; }

        public List<ConcentrationVM> Concentration { get; set; }

    }
}

FTCS/FTCS/Controllers/ProgramOfStudyController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;
using FTCS.Services;
using FTCS.Services.Implementation;
using FTCS.Services.Interfaces;
using FTCS.ViewModels;
using FTCS.ViewModels.Task;
using Microsoft.AspNet.Identity;

namespace FTCS.Controllers
{
    public class ProgramOfStudyController : Controller
    {
        private readonly ICredentialManagerService _credentialManagerService;
        private readonly IDepartmentService _departmentService;

        public ProgramOfStudyController()
        {
            _credentialManagerService = new CredentialManagerService();
            _departmentService = new DepartmentService();
        }

        public ProgramOfStudyController(ICredentialManagerService credentialManagerService, IDepartmentService departmentService)
        {
            _credentialManagerService = credentialManagerService;
            _departmentService = departmentService;

        }

        public ActionResult Index()
        {
            var identity = (ClaimsIdentity)User.Identity;
            IEnumerable<ProgramsVM> listOfPrograms;
            if (!string.IsNullOrEmpty(identity.FindFirstValue(FTCSUserManager.CollegeClaim)))
            {
                var college = identity.FindFirstValue(FTCSUserManager.CollegeClaim);
                listOfPrograms = _credentialManagerService.GetProgramsOfStudyForCollege(college);
            }
            else if (!string.IsNullOrEmpty(identity.FindFirstValue(FTCSUserManager.DepartmentClaim)))
            {
                var department = identity.FindFirstValue(FTCSUserManager.DepartmentClaim);
                listOfPrograms = _credentialManagerService.GetProgramsOfStudyForDepartment(department);
            }
            else
            {
                throw new HttpException(402, "Credential Officer does not have valid Credentials");
            }

            return PartialView("_ProgramsOfStudy", listOfPrograms);
        }

        public ActionResult AddProgramOfStudy()
        {
            List<SelectListItem> listOfDepartments = new List<SelectListItem>();
            var identity = (ClaimsIdentity)User.Identity;
            var department = identity.FindFirstValue(FTCSUserManager.DepartmentClaim);
            var college = identity.FindFirstValue(FTCSUserManager.CollegeClaim);
            if (college != null && identity.FindFirstValue(ClaimTypes.Role) == RoleType.Dean.ToString())
            {
                listOfDepartments.AddRange(_departmentService.GetListOfDepartmentSelectListItems());
            }

            var model = new AddProgramOfStudyVM()
            {
                SelectProgram = _credentialManagerService.GetProgramOptions(),
                SelectLevel = _credentialManagerService.GetLevelOptions(),
                SelectCoordinator = _credentialManagerService.GetCoordinatorOptions(department, college),
                SelectDepartment = listOfDepartments
            };

            return PartialView("_AddForm", model);
        }
        public ActionResult AddProgramOfStudyButton()
        {
            return PartialView("_AddButton");
        }

        [HttpPost]
        public ActionResult AddProgramofStudy(string programCode, string levelId, string coordinatorId, string departmentCode)
        {
            if (departmentCode == null)
            {
                departmentCode = ((ClaimsIdentity) User.Identity).FindFirstValue(FTCSUserManager.DepartmentClaim);
            }
            var response = _credentialManagerService.AddNewProgramOfStudy(programCode, levelId, coordinatorId, departmentCode);
            return RedirectToAction("Index", "Task");

        }

        [RoleAuthorize(Roles = "Chair")]
        public ActionResult RemoveProgramOfStudy(string coordinatorid, string programcode)
        {
            _credentialManagerService.DeleteProgramOfStudy(programcode, coordinatorid);
            return RedirectToAction("Index");
        }

        [HttpPost]
        [RoleAuthorize(Roles = "Chair")]
        public ActionResult ChangeProgramCoordinator(ProgramsVM vmInfo)
        {
            if (ModelState.IsValid)
            {
                _credentialManagerService.ChangeCoordinatorForProgramOfStudy(vmInfo.ProgramCode,
                vmInfo.CoordinatorId);
                var model = _credentialManagerService.GetProgramOfStudy(vmInfo.ProgramCode, vmInfo.DepartmentCode);
                return PartialView("_AccordionButton", model);
            }
            var errors = string.Join(",", ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage));
            Response.StatusCode = 402;
            return Content(errors);


        }

        public ActionResult ShowProgramOfStudyContent(string programCode, string departmentCode)
        {
            var model = _credentialManagerService.GetProgramOfStudy(programCode, departmentCode);
            return PartialView("_AccordionButton", model);
        }

        public ActionResult ShowChangeProgramCoordinator(string programCode, string departmentCode)
        {
            var identity = (ClaimsIdentity)User.Identity;
            var department = identity.FindFirstValue(FTCSUserManager.DepartmentClaim);
            var college = identity.FindFirstValue(FTCSUserManager.CollegeClaim);
            ViewData["CoordinatorOptions"] = _credentialManagerService.GetCoordinatorOptions(department, college);
            var model = _credentialManagerService.GetProgramOfStudy(programCode, departmentCode);
            return PartialView("_EditCoordinator", model);
        }

        public ActionResult ShowProgramOfStudyConcentration(string programCode)
        {
            var concentrations = _credentialManagerService.GetProgramConcentrations(programCode);
            return PartialView("_ConcentrationTable", concentrations);
        }

        public ActionResult ShowNormalProgramOfStudyConcentration(string programCode, string concentrationCode)
        {
            var model = _credentialManagerService.GetProgramConcentration(programCode, concentrationCode);
            return PartialView("_Concentration", model);
        }

        public ActionResult ShowChangeProgramOfStudyConcentration(string programCode, string concentrationCode)
        {
            var identity = (ClaimsIdentity)User.Identity;
            var department = identity.FindFirstValue(FTCSUserManager.DepartmentClaim);
            var college = identity.FindFirstValue(FTCSUserManager.CollegeClaim);
            ViewData["CoordinatorOptions"] = _credentialManagerService.GetCoordinatorOptions(department, college);
            var model = _credentialManagerService.GetProgramConcentration(programCode, concentrationCode);
            return PartialView("_EditConcentration", model);
        }
        [HttpPost]
        public ActionResult ChangeConcentrationCoordinator(ConcentrationVM vmInfo)
        {
            if (ModelState.IsValid)
            {
                _credentialManagerService.ChangeCoordinatorForConcentration(vmInfo.ConcentrationCode,
                vmInfo.ProgramCode, vmInfo.CoordinatorId);
                var model = _credentialManagerService.GetProgramConcentration(vmInfo.ProgramCode, vmInfo.ConcentrationCode);
                return PartialView("_Concentration", model);
            }
            var errors = string.Join(",", ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage));
            Response.StatusCode = 402;
            return Content(errors);

        }
    }
}

FTCS/FTCS/Views/ProgramOfStudy/_AccordionButton.cshtml
@model ProgramsVM
@using FTCS.ViewModels.Task;

<!--Cordinator-->
<div class="center-contents col-lg-4 col-md-5 col-sm-4 col-xs-3 ellipsis" title="@Model.Coordinator">
    <!--Used a-tag becasue of icon-->
    <a id="pencil"
       title="Change the coordinator for @Model.Program"
       data-ajax="true"
       data-ajax-method="GET"
       data-ajax-mode="replace"
       data-ajax-loading="#ajax-loading-@Model.ProgramCode"
       data-ajax-update="#accordion-button-contents-@Model.ProgramCode"
       href=@Url.Action("ShowChangeProgramCoordinator", new {programCode = Model.ProgramCode, departmentCode = Model.DepartmentCode})
       style="padding-right: .5rem">
        <i class="fa fa-pencil" aria-hidden="true"></i>
    </a>
    Coord: @Model.Coordinator
    <!--Loading wheel-->
    <div id="ajax-loading-@Model.ProgramCode" class="ajax-loader-wheel-sm" style="display:none">
    </div>
</div>
<!--Level-->
<div title="@Model.Level" class="center-contents col-lg-2 col-md-1 ellipsis">
    @Model.Level
</div>
<!--Number of concentrations-->
<div class="center-contents col-md-1 col-right" title="There are @Model.NumberOfConcentrations concentration(s) in the @Model.Program program of study">
    <div class="badge">
        @Model.NumberOfConcentrations
    </div>
</div>

FTCS/FTCS/Views/ProgramOfStudy/_AddButton.cshtml
<!--Button for adding a program of study-->
<!--Made into a partial for AJAX functionally-->
<!--Used  a-tag because of the icon-->
<a data-ajax="true" 
   data-ajax-method="GET" 
   data-ajax-mode="replace" 
   data-ajax-complete="setupAddProgramSection()"
   data-ajax-loading="#ajax-loading-add-pos"
   data-ajax-update="#add-program-of-study" 
   href=@Url.Action("AddProgramOfStudy")
   class="btn rounded-dashed-button add-program-button">
   <i class="fa fa-plus-circle" aria-hidden="true" style="padding-right: 1rem;"></i>
    Add a Program of Study
    <div id="ajax-loading-add-pos" class="ajax-loader-wheel-lg" style="display:none">
    </div>
</a>

FTCS/FTCS/Views/ProgramOfStudy/_AddForm.cshtml
@model FTCS.ViewModels.AddProgramOfStudyVM

<div class="rounded-dashed-container">
    @using (@Html.BeginForm("AddProgramOfStudy", "ProgramOfStudy", FormMethod.Post, new {@id = "add-program-of-study"}))
    {
        <div class="add-program-of-study-form">
            <div class="row">
                <!--Form title-->
                <h2 class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    Add a Program of Study
                </h2>
            </div>
            <!--Drop-downs for program, level, department and coordinator-->
            <div class="row">
                <label class="label-small col-lg-3 col-md-3 col-sm-3 col-xs-3 col-right">
                    Program:
                </label>
                @Html.DropDownList("ProgramCode", Model.SelectProgram,
                    new {@class = "select-box glow-blue col-lg-8 col-md-8 col-sm-8 col-xs-8 col-right", @title = "Select a Program"})
            </div>
            <div class="row padding-top-2">
                <label class="label-small col-lg-3 col-md-3 col-sm-3 col-xs-3 col-right">
                    Level:
                </label>
                @Html.DropDownList("LevelId", Model.SelectLevel,
                    new {@class = "select-box glow-blue col-lg-8 col-md-8 col-sm-8 col-xs-8 col-right", @title = "Select a Level"})
            </div>
            @if (Model.SelectDepartment.Any())
            {
                <div class="row padding-top-2">
                    <label class="label-small col-lg-3 col-md-3 col-sm-3 col-xs-3 col-right">
                        Department:
                    </label>
                    @Html.DropDownList("DepartmentCode", Model.SelectDepartment,
                        new {@class = "select-box glow-blue col-lg-8 col-md-8 col-sm-8 col-xs-8 col-right", @title = "Select a Department"})
                </div>
            }
            <div class="row padding-top-2">
                <label class="label-small col-lg-3 col-md-3 col-sm-3 col-xs-3 col-right">
                    Coordinator:
                </label>
                @Html.DropDownList("CoordinatorId", Model.SelectCoordinator,
                    new {@class = "select-box glow-blue col-lg-8 col-md-8 col-sm-8 col-xs-8 col-right", @title = "Select a Coordinator"})
            </div>
        </div>
        <div class="row padding-top-2" >
            <div class="col-lg-offset-4 col-md-offset-4 col-sm-offset-4 col-lg-4 col-md-4 col-sm-4 col-xs-4" style="text-align: center;">
                <!--Sumbit-->
                <button id="report-filter-submit" class="btn rounded-green-button shadow-box-gray" disabled="disabled" type="submit" title="Submit Program of Study">
                    <i class="fa fa-check" aria-hidden="true"></i>
                </button>
                <!--Cancel-->
                <!--Used a-tag because of icon-->
                <a data-ajax="true" 
                   data-ajax-method="GET" 
                   data-ajax-mode="replace" 
                   data-ajax-update="#add-program-of-study"
                   data-ajax-complete="loadProgramForm()" 
                   href=@Url.Action("AddProgramOfStudyButton")
                   class="btn rounded-red-button shadow-box-gray" 
                   title="Do not add Program of Study">
                    <i class="fa fa-times" aria-hidden="true"></i>
                </a>
            </div>
        </div>
    }
</div>

FTCS/FTCS/Views/ProgramOfStudy/_Concentration.cshtml
@model FTCS.ViewModels.ConcentrationVM

<!--Concentration name-->
<td class="ellipsis" title="@Model.Program">
    @Model.Program
</td>
<!--Coordinator name-->
<td class="ellipsis" title="@Model.Coordinator">
    @Model.Coordinator
</td>
<td class="col-right">
    <!--Loader wheel-->
    <div id="ajax-loading-@Model.ConcentrationCode-@Model.ProgramCode" class="ajax-loader-wheel-md" style="display: none">
    </div>
    <!--Edit button-->
    <!--Used a-tag because of icon-->
    <a class="btn rounded-teal-button shadow-box-gray" title="Edit the @Model.ConcentrationCode concentration"
       data-ajax="true"
       data-ajax-method="GET"
       data-ajax-mode="replace"
       data-ajax-loading="#ajax-loading-@Model.ConcentrationCode-@Model.ProgramCode"
       data-ajax-update="#concentration-@Model.ConcentrationCode-@Model.ProgramCode"
       href=@Url.Action("ShowChangeProgramOfStudyConcentration", new {programCode = Model.ProgramCode, concentrationCode=Model.ConcentrationCode})>
        <i class="fa fa-pencil" aria-hidden="true"></i>
    </a>
</td>

FTCS/FTCS/Views/ProgramOfStudy/_ConcentrationTable.cshtml
@model  IEnumerable<ConcentrationVM>
@using FTCS.ViewModels;

<!--Made a partial so concentration table contents can have AJAX functionality-->
<!--Just the contents needs to be updated not the whole view or program of study-->
@foreach (var concentration in Model)
{
    <!--id is used in a different view for an AJAX call-->
    <tr id="concentration-@concentration.ConcentrationCode-@concentration.ProgramCode">
        @Html.Partial("_Concentration", concentration)
    </tr>
}

FTCS/FTCS/Views/ProgramOfStudy/_DeleteConfirm.cshtml
@model FTCS.ViewModels.Task.ProgramsVM

<div class="block-ui-delete" style="display: none">
    <div class="remove-body">
        <div class="row">
            <!--Title-->
            <h2>Remove @Model.Program</h2>
        </div>
        <hr />
        <div class="row">
            <!--Message-->
            <p>Are you sure you want to remove @Model.Program from the @Model.DepartmentCode department?</p>
        </div>
        <hr />
        <div class="row">
            <div class="col-lg-offset-4 col-md-offset-4 col-sm-offset-4 col-lg-4 col-md-4 col-sm-4 col-xs-4">
                <!--Accept button-->
                <!--Used a-tag because of icon-->
                <a class="btn rounded-green-button shadow-box-gray"
                   onclick="fadeOut()"
                   data-ajax="true"
                   data-ajax-method="GET"
                   data-ajax-mode="replace"
                   data-ajax-loading="#loading-wheel"
                   data-ajax-update="#task-panel"
                   data-ajax-success="ajaxSuccessDelete()"
                   href=@Url.Action("RemoveProgramOfStudy", new {coordinatorid = Model.CoordinatorId, programcode = Model.ProgramCode})
                   title="Confirm removal">
                    <i class="fa fa-check" aria-hidden="true"></i>
                </a>
                <!--Cancel button-->
                <button class="btn rounded-red-button shadow-box-gray" onclick="fadeOut()" title="Cancel removal">
                    <i class="fa fa-times" aria-hidden="true"></i>
                </button>
            </div>
        </div>
    </div>
</div>

FTCS/FTCS/Views/ProgramOfStudy/_EditConcentration.cshtml
@model FTCS.ViewModels.ConcentrationVM
@using FTCS.ViewModels.Task;

<td colspan="3">
    @using (@Ajax.BeginForm("ChangeConcentrationCoordinator", "ProgramOfStudy", new AjaxOptions()
    {
        HttpMethod = "POST",
        InsertionMode = InsertionMode.Replace,
        UpdateTargetId = "concentration-" + Model.ConcentrationCode + "-" + Model.ProgramCode,
        OnSuccess = "ajaxSuccessCON()",
        OnFailure = "ajaxError(xhr,status, error)",
        LoadingElementId = "ajax-loading-" + Model.ConcentrationCode + "-" + Model.ProgramCode
    }))
    {
        <!--Concentration-->
        <div class="col-md-4" style="padding-top: .7rem;" title="@Model.Program">
            @Model.Program
        </div>
        <!--Select box for coordinator-->
        <div class="col-md-4">
            @Html.HiddenFor(model => Model.ConcentrationCode)
            @Html.HiddenFor(model => Model.ProgramCode)
            @Html.DropDownListFor(model => Model.CoordinatorId, ViewData["CoordinatorOptions"] as List<SelectListItem>, new {@class = "select-box", @title = "Select a Coordinator"})
        </div>
        <div class="col-md-4 col-right">
            <!--Loader wheel-->
            <div id="ajax-loading-@Model.ConcentrationCode-@Model.ProgramCode" class="ajax-loader-wheel-md" style="display: none">
            </div>
            <!--Sumbit button-->
            <button class="btn rounded-green-button shadow-box-gray" type="submit" title="Submit change to @Model.Program">
                <i class="fa fa-check" aria-hidden="true"></i>
            </button>
            <!--Cancel button-->
            <!--Used a-tag because of icon-->
            <a class="btn rounded-red-button shadow-box-gray" title="Cancel change for @Model.Program"
               data-ajax="true"
               data-ajax-method="GET"
               data-ajax-mode="replace"
               data-ajax-loading="#ajax-loading-@Model.ConcentrationCode-@Model.ProgramCode"
               data-ajax-update="#concentration-@Model.ConcentrationCode-@Model.ProgramCode"
               href=@Url.Action("ShowNormalProgramOfStudyConcentration", new {programCode = Model.ProgramCode, concentrationCode = Model.ConcentrationCode})>
                <i class="fa fa-times" aria-hidden="true"></i>
            </a>
        </div>
    }
</td>

FTCS/FTCS/Views/ProgramOfStudy/_EditCoordinator.cshtml
@model ProgramsVM
@using FTCS.ViewModels.Task;

<div class="program-of-study-contents center-contents">
    @using (Ajax.BeginForm("ChangeProgramCoordinator", "ProgramOfStudy", new AjaxOptions()
    {
        HttpMethod = "POST",
        InsertionMode = InsertionMode.Replace,
        UpdateTargetId= "accordion-button-contents-" + Model.ProgramCode,
        OnSuccess = "ajaxSuccessPOS()",
        OnFailure = "ajaxError(xhr, status, error)",
        LoadingElementId = "ajax-loading-" + Model.ProgramCode

    }))
    {
        <!--Edit Coordinator-->
        <div class="center-contents col-lg-5 col-md-5 col-sm-5 col-xs-5" style="padding-left: 3rem;" title="Select a coordinator for @Model.Program">
            Coord:
            @Html.HiddenFor(model => Model.ProgramCode)
            @Html.HiddenFor(model => Model.DepartmentCode)
            @Html.DropDownListFor(model => Model.CoordinatorId, ViewData["CoordinatorOptions"] as List<SelectListItem>, new {@class = "select-box", @style = "margin-left:.5rem;" })
            <!--Loader wheel-->
            <div id="ajax-loading-@Model.ProgramCode" class="ajax-loader-wheel-sm" style="display:none">
            </div>
        </div>
        <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2 col-right center-contents">
            <!--Submit button-->
            <button class="btn rounded-green-button shadow-box-blue" type="submit" title="Sumbit change for @Model.Program">
                <i class="fa fa-check" aria-hidden="true"></i>
            </button>
            <!--Cancel button-->
            <!--Used a-tag because of icon-->
            <a class="btn rounded-red-button shadow-box-blue" title="Cancel change for @Model.Program"
               data-ajax="true"
               data-ajax-method="GET"
               data-ajax-mode="replace"
               data-ajax-loading="#ajax-loading-@Model.ProgramCode"
               data-ajax-update="#accordion-button-contents-@Model.ProgramCode"
               href=@Url.Action("ShowProgramOfStudyContent",new {programCode = Model.ProgramCode, departmentCode = Model.DepartmentCode})>
                <i class="fa fa-times" aria-hidden="true"></i>
            </a>
        </div>
    } 
</div>

FTCS/FTCS/Views/ProgramOfStudy/_ProgramsOfStudy.cshtml
@model IEnumerable<ProgramsVM>
@using FTCS.ViewModels.Task;

@foreach (var programOfStudy in Model)
{
    <div class="row padding-top-4">
        <div class="program-of-study">
            
            <!--Accordion button-->
            <div class="btn rounded-blue-button shadow-box-gray closed program-of-study-contents">
                <!--Open/Close indicator and Program of study name-->
                <div class="btn program-of-study-button col-lg-5 col-md-5 col-sm-6 col-xs-7 center-contents" title="@programOfStudy.Program">
                    <i class="chevron fa fa-chevron-right" aria-hidden="true"></i>
                    <i class="chevron fa fa-chevron-down" style="display: none;" aria-hidden="true"></i>
                    <label>
                        @programOfStudy.Program
                    </label>
                </div>
                <div id="accordion-button-contents-@programOfStudy.ProgramCode" class="center-contents">
                    @Html.Partial("_AccordionButton", programOfStudy)
                </div>
            </div>
            <!--Accordion panel -->
            <div class="panel closed">
                <!--Content table-->
                <table class="table">
                    <thead>
                    <tr>
                        <th class="col-lg-4 col-md-4 col-sm-4 col-xs-4">Concentration</th>
                        <th class="col-lg-4 col-md-4 col-sm-4 col-xs-4">Coordinator</th>
                        <th class="col-lg-4 col-md-4 col-sm-4 col-xs-4"></th>
                    </tr>
                    </thead>
                    <tbody>
                    @Html.Action("ShowProgramOfStudyConcentration", new {programCode = programOfStudy.ProgramCode})
                    </tbody>
                </table>
                <!--Delete link-->
                <div class="row">
                    <button class="btn delete shadow-box-gray" onclick="fadeIn(this)" title="Remove the @programOfStudy.Program program of study">
                        Remove @programOfStudy.Program from the @programOfStudy.DepartmentCode department
                    </button>
                    @Html.Partial("_DeleteConfirm", programOfStudy)
                </div>
            </div>
        </div>
    </div>
}
<!--Add program of study-->
<div id="add-program-of-study" class="row padding-top-2" style="text-align: center;">
    @Html.Action("AddProgramOfStudyButton")
</div>
 
<!--Success messages-->
<div id="ajax-success-pos" class="ajax-success" style="display: none">
    <i class="fa fa-check-square-o" aria-hidden="true"></i>
    The program coordinator was successfully changed!
</div>

<div id="ajax-success-con" class="ajax-success" style="display: none">
    <i class="fa fa-check-square-o" aria-hidden="true"></i>
    A concentration coordinator was successfully changed!
</div>

<div id="ajax-success-delete" class="ajax-success" style="display: none">
    <i class="fa fa-check-square-o" aria-hidden="true"></i>
    The program of study has been removed!
</div>


<!--Script to make accordion drop down-->
@Scripts.Render("~/Scripts/FTCS/program-of-study-accordion.js")
@Scripts.Render("~/Scripts/FTCS/remove-fade-in-fade-out.js")