FTCS/FTCS/Controllers/SharedController.cs
using FTCS.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FTCS.Views.Shared
{
    public class SharedController : Controller
    {
        // GET: Shared
        public ActionResult RenderNavBar()
        {
            return PartialView("_NavBar");
        }
        public ActionResult RenderSemesterYear()
        {
            NavBarVM viewModel = new NavBarVM();
            var month = DateTime.Now.Month;
            viewModel.SetSemesterAndYear(month);
            return PartialView("_SemesterAndYear", viewModel);
        }
    }
}

FTCS/FTCS/Views/Shared/_FilterBar.cshtml
@model  FilterBarVM
@using FTCS.ViewModels;
@using FTCS.App_Code;

@{
    var isAllSelected = new Func<bool>(() => "All" == Model.Letter);
}

<div id="filter-bar">
    <div class="row">
        <!--Starting with Label-->
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 col-left @CSSHelper.hideIf(isAllSelected)">
            <p id="starts-with-message">
                @ViewBag.Title starting with: @Model.Letter
            </p>
        </div>
    </div>
    <div class="row padding-top-2">
        <!--A-Z Filter-->
        <div id="filter-letters" class="col-lg-7 col-md-12 col-sm-12 col-xs-12 col-left">
            <div class="btn-group" role="group">
                @Html.ActionLink("All", "Index", new { Letter = "All", Search = Model.Search },
                    new { @class = "btn filter-letter-button rounded-blue-button shadow-box-gray " + @CSSHelper.activeIf(Model.Letter == "All") })
                @for (var c = 'A'; c <= 'Y'; c++)
                {
                    @Html.ActionLink(@c.ToString(), "Index",
                            new { Letter = @c.ToString(), Search = Model.Search, Department = Model.Department },
                                new { @class = "btn filter-letter-button rounded-blue-button shadow-box-gray " + @CSSHelper.activeIf(c.ToString() == Model.Letter) })
                }
                @Html.ActionLink("Z", "Index", new { Letter = "Z", Search = Model.Search, Department = Model.Department },
                    new { @class = "btn filter-letter-button rounded-blue-button shadow-box-gray " + @CSSHelper.activeIf("Z" == Model.Letter) })
            </div>
        </div>
        <!--Search Bar-->
        <div id="search-box" class="col-lg-5 col-md-12 col-sm-12 col-xs-12 col-right" style="white-space:nowrap">

            @using (Html.BeginForm("Index", null, FormMethod.Get))
            {
                @Html.HiddenFor(model => model.Letter);
                @Html.HiddenFor(model => model.Sort)
                @Html.HiddenFor(model => model.Department)
                <div class="btn-group col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    @Html.TextBoxFor(model => model.Search, new { id = "search-text-box", @class = "form-control filter-search-box" })
                    <input id="search-button" class="btn rounded-white-button" type="submit" value="">
                </div>
            }
        </div>
    </div>
    <!--Clear Button-->
    <div class="row padding-top-2 padding-bottom-2">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 col-left">
            @Html.ActionLink("Clear", "Index", new { }, new { @class = "btn filter-clear rounded-border-blue-button shadow-box-gray" })
        </div>
    </div>
</div>

FTCS/FTCS/Views/Shared/_Layout.cshtml
@using System.Security.Claims
@using FTCS.Services
@using Microsoft.AspNet.Identity
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
@{
    var identity = (ClaimsIdentity) User.Identity;
}
<!--Loader-->
<div id="loading-wheel" class="block-ui">
    <div class="loader">
        <div class="loader-wheel"></div>
        Loading...
    </div>
</div>
<div id="ajax-success" class="ajax-success" style="display: none;">
    <i class="fa fa-check-square-o" aria-hidden="true"></i>
    
</div>
<div id="ajax-error" class="ajax-error" style="display: none;">
    <i class="fa fa-close" aria-hidden="true"></i>
</div>
<!--Header Section-->
<div id="site-header" class="container">
    <div class="row">
        <!--Semester Year-->
        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3 col-left">
            <div class="row">
                @Html.Action("RenderSemesterYear", "Shared")
            </div>
        </div>
        <!--Logo and Title-->
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 col-centered">
            <a id="etsu-logo" href="http://www.etsu.edu/etsuhome/default.aspx">
                <img src="~/Content/Images/header_logo_2014_alt.png"/>
            </a>
            @Html.ActionLink("Faculty Teaching Credentials System", "Index", "Home", new {},
                new {id = "header-title"})
        </div>
        <!--Login and Logout-->
        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3 col-right">
            @if (string.IsNullOrEmpty(User.Identity.Name))
            {
                @Html.ActionLink("Log in", "Login", "Account", new {},
                    new {@class = "btn rounded-border-yellow-button shadow-box-blue", @id = "login-link"})
            }
            else
            {
                <div class="row">
                    <div class="officer-dropdown">
                        <button class="btn rounded-blue-button officer-option-button" onclick="officerMenuOpenClose()">
                            Hello, @User.Identity.Name <i class="fa fa-caret-down" onclick="officerMenuOpenClose()" aria-hidden="true"></i>
                        </button>
                        <div id="officer-dropdown-content" class="officer-dropdown-content">
                            @Html.ActionLink("Credential Tasks", "Index", "Task", new {},
                                new {@id = "credentialing-task-link"})
                            @Html.ActionLink("Log out", "Logout", "Account", new {},
                                new {@id = "logout-link"})
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="login-role">
                        @if (User.IsInRole("Chair"))
                        {
                            <label>Department Credentials Officer in</label>
                            <label><strong>@identity.FindFirstValue(FTCSUserManager.DepartmentClaim)</strong></label>
                        }
                        else if (User.IsInRole("Dean"))
                        {
                            <label>College Credentials Officer</label>
                        }
                        else if (User.IsInRole("Administrator"))
                        {
                            <label>Proxy</label>
                        }

                    </div>
                </div>
            }
        </div>
    </div>
    <!--Nav-Bar Section-->
    <div id="nav-bar">
        <div class="row row-centered padding-top-2" style="max-width: 1400px">
            @Html.Action("RenderNavBar", "Shared")
        </div>
    </div>
</div>
<!--Body Section-->
<div class="body-content">
    <div class="card">
        @RenderBody()
    </div>
</div>
<!--Footer Section-->
<div>
    <footer id="footer-upper"><!--This is here so the mountain background can have a place--></footer>
    <footer id="footer-bottom" class="col-centered">
        <p>@Html.ActionLink("Contact Us", "", "", new {}, new { id = "contact-us-link"})</p>
        <p>&copy; @DateTime.Now.Year<a href="http://www.etsu.edu/etsuhome/"> East Tennessee State University</a> All Rights Reserved (FTCS v2.0)
        </p>
    </footer>
</div>
<!--Script Section-->
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@Scripts.Render("~/bundles/jqueryval")
@Scripts.Render("~/bundles/ftcs-scripts")
@RenderSection("scripts", required: false)
@Scripts.Render("~/Scripts/FTCS/loader.js")
@Scripts.Render("~/Scripts/FTCS/officer-option-dropdown.js")

</body>
</html>

FTCS/FTCS/Views/Shared/_NavBar.cshtml
<!--Home Button Button-->
<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3 col-centered">
    @Html.ActionLink("Home", "Index", "Home", new { }, 
        new { id = "home-link", @class = "btn nav-bar-button rounded-yellow-button shadow-box-blue" })
</div>
<!--Search By Button-->
<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3 col-centered dropdown">
    <button id="search-faculty-link" class="btn nav-bar-button rounded-yellow-button">
        Search for Faculty
        <i class="fa fa-caret-down" aria-hidden="true"></i>
    </button>
    <div class="dropdown-content">
        <ul>
            <li>
                @Html.ActionLink("By Departments", "Index", "Department", new { search = "", letter = "" }, new { id = "search-by-department-link" })
            </li>
            <li>
                @Html.ActionLink("By Name", "Index", "Faculty", new { search = "", letter = "" }, new { id = "search-by-faculty-link" })
            </li>
            <li class="dropdown-content-last">
                @Html.ActionLink("By Course", "Index", "Course", new { search = "", sort = "Name_asc", letter = "" }, new { id = "search-by-course-link" })
            </li>
        </ul>
    </div>
</div>
<!--Reports Button-->
<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3 col-centered dropdown">
    <button id="reports-link" class="btn nav-bar-button rounded-yellow-button">
        Reports
        <i class="fa fa-caret-down" aria-hidden="true"></i>
    </button>
    <div class="dropdown-content">
        <ul>
            <li>
                <a id="course-section-qualifications-link" href="@Url.Action("CourseSectionQualificationPercentageReport", "Reports")"> Course Section Qualifications Percentage Report </a>
            </li>
            <li>
                <a id="faculty-credentials-report-link" href="@Url.Action("FacultyCredentialsReport", "Reports")">Faculty Credentials Report</a>
            </li>
            <li>
                <a id="faculty-roster-link" href="@Url.Action("FacultyRoster","Reports")"> Faculty Roster Report </a>
            </li>
            <li>
                <a id="graduate-assistant-roster-link" href="@Url.Action("GradAssistantRoster","Reports")"> Graduate Assistant Roster Report </a>
            </li>
        </ul>
    </div>
</div>
<!--Guidelines and Instructions Button-->
<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3 col-centered dropdown">
    <button id="guidelines-and-instructions-link" class="btn nav-bar-button rounded-yellow-button">
        Guidelines/Instructions
        <i class="fa fa-caret-down" aria-hidden="true"></i>
    </button>
    <div class="dropdown-content">
        <ul>
            <li>
                <a id="etsu-mission-link" href="https://www.etsu.edu/president/mission.php" target="_blank"> ETSU Mission <i class="fa fa-external-link"></i></a>
            </li>
            <li>
                <a id="teaching-credential-standards-link" href="~/Documents/TeachingCredentialStandards.pdf" target="_blank"> Teaching Credential Standards <i class="fa fa-file-pdf-o"></i></a>
            </li>
            <li>
                <a id="sacs-guidelines-link" href="~/Documents/SACS.pdf" target="_blank">SACS Guidelines <i class="fa fa-file-pdf-o"></i></a>
            </li>
            <li>
                <a id="chair-instructions-link" href=@Url.Action("Index","ProfessionalQualifications") target="_blank">Chair Instructions <i class="fa fa-external-link"></i></a>
            </li>
            <li>
                <a id="graduate-faculty-appointment-guidelines-link" href="~/Documents/gradfacproc212.pdf" target="_blank">Graduate Faculty Appointment Guidelines <i class="fa fa-file-pdf-o"></i></a>
            </li>
        </ul>
    </div>
</div>

FTCS/FTCS/Views/Shared/_SemesterAndYear.cshtml
@model FTCS.ViewModels.NavBarVM

<div id="semester-year" class="col-lg-6 col-md-6 col-sm-6 col-xs-6 col-left padding-left-2">
    @Html.DisplayFor(sy => sy.SemesterAndYear)
</div>